-- TABELA DE USUARIOS
CREATE TABLE IF NOT EXISTS USUARIOS 
	(
		codigo	INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY
		,nome	VARCHAR(20) NOT NULL
		,senha	VARCHAR(200) NOT NULL
		,tipo	VARCHAR(20) NOT NULL
		,email	VARCHAR(200) NOT NULL
	)
;